language: python
dist: xenial   # required for Python >= 3.7
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
  - pip uninstall -y pytest-isort
# command to run tests
script: pytest --pep8 -s
